V1.0
clio-app/clio-ios-app pull request #42
Opened 2023-11-10 11:59 UTC by ThiagoHBA

2023-11-10 12:09 UTC, lvasantos requested changes
The philosophy prompts from JSON will not go to V1.0

2023-11-10 12:09 UTC, lvasantos commented on clio-app/Resource/en.lproj/ThemePhrases.json
> +    "Philosophy": [
Philosophy should be excluded.

2023-11-10 12:09 UTC, lvasantos commented on clio-app/Resource/pt-BR.lproj/ThemePhrases.json
> +    "Filosofia": [
Filosofia should be excluded

2023-11-12 16:27 UTC, BeatrizLdS approved these changes
LGTM!

2023-11-14 11:48 UTC, lvasantos approved these changes

2023-11-14 12:02 UTC, merged